version: '3'
services:
  docker-app:
    image: viniciuscluna/letscode-venda
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=prod
    depends_on:
      - docker-mongo
  docker-mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty